### ISSUE TITLE
Can`t build on ubuntu 14.04

### ISSUE THREAD

**Issue by neochapay** [nemomobile/mapplauncherd#23]
[ 35%] Building CXX object src/launcherlib/CMakeFiles/applauncherd.dir/appdata.cpp.o
In file included from /home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp:20:0:
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.h:114:17: error: 'uid_t' has not been declared
     void setIDs(uid_t userId, gid_t groupId);
                 ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.h:114:31: error: 'gid_t' has not been declared
     void setIDs(uid_t userId, gid_t groupId);
                               ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.h:117:5: error: 'uid_t' does not name a type
     uid_t userId() const;
     ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.h:120:5: error: 'gid_t' does not name a type
     gid_t groupId() const;
     ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.h:136:5: error: 'gid_t' does not name a type
     gid_t       m_gid;
     ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.h:137:5: error: 'uid_t' does not name a type
     uid_t       m_uid;
     ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp: In constructor 'AppData::AppData()':
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp:34:5: error: class 'AppData' does not have any field named 'm_gid'
     m_gid(0),
     ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp:35:5: error: class 'AppData' does not have any field named 'm_uid'
     m_uid(0)
     ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp: At global scope:
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp:148:22: error: variable or field 'setIDs' declared void
 void AppData::setIDs(uid_t userId, gid_t groupId)
                      ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp:148:22: error: 'uid_t' was not declared in this scope
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp:148:36: error: 'gid_t' was not declared in this scope
 void AppData::setIDs(uid_t userId, gid_t groupId)
                                    ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp:154:1: error: 'uid_t' does not name a type
 uid_t AppData::userId() const
 ^
/home/avis/NEMO/mapplauncherd/src/launcherlib/appdata.cpp:159:1: error: 'gid_t' does not name a type
 gid_t AppData::groupId() const
 ^
make[2]: **\* [src/launcherlib/CMakeFiles/applauncherd.dir/appdata.cpp.o] Error 1
make[1]: **\* [src/launcherlib/CMakeFiles/applauncherd.dir/all] Error 2
